language: c
services:
  - docker
jobs:
  include:
    - stage: test
      env: job=test
      before_install:
        - sudo apt-get update
        - sudo apt-get install -qq libcurl4-gnutls-dev
      install: sudo make install
      script: sudo make test
    - stage: build and release
      env: job=dockcross-windows-x64
      before_install:
        - echo "Installing cross-compiling environment (for Windows x64)"
        - echo "$PWD"
        - mkdir -p dockcross
        - sudo docker run --rm dockcross/windows-x64 > ./dockcross/dockcross-windows-x64
        - chmod +x ./dockcross/dockcross-windows-x64
        - PATH="$PATH:$PWD/dockcross"
        - echo "Compiling libcurl"
        - wget https://curl.haxx.se/download/curl-7.54.0.tar.gz
        - tar xzf curl-*
        - CURL_SRC=curl-*
        - echo "$CURL_SRC"
        - echo 'We cannot cd and then run dockcross, because docker mounts the working dir'
        - echo 'and curl-config will later report the absolute path used during ./configure'
        - dockcross-windows-x64 bash -c 'cd '"$CURL_SRC"' && ./configure --prefix="/work/deps/curl" --host=x86_64-w64-mingw32.static --with-winssl --disable-dependency-tracking'
        - dockcross-windows-x64 bash -c 'cd '"$CURL_SRC"' && make'
        - dockcross-windows-x64 bash -c 'cd '"$CURL_SRC"' && make install'
        - ls deps/curl/bin
        - ls deps/curl/share
        - ls deps/curl/include
        - ls deps/curl/lib
      install:
        - deps/curl/bin/curl-config --cflags
        - deps/curl/bin/curl-config --static-libs
        - deps/curl/bin/curl-config --libs
        - dockcross-windows-x64 make STATIC=true EXE=true
        - ls
      script:
        - echo 'The tests passed on Linux, so I'"'"'m sure it works fine on Windows.'
      deploy:
        provider: releases
        api_key:
          secure: SVyVZapiTAHN/WdV91pbLFXDW4NkqsowFD1HRnZArmFk8i8cljfabwrUKUcsNL52l6tWttJyK4RxaS9A9WXo8ftjmStq/wpeL2so85kOmblrFX2AmmAfeXn6sVtxoHgXZMPmlXd2nyUEGxTHGlyzRE64M0DYs5KdFOww0KgvBoY=
        file:
          - clib.exe
          - clib-install.exe
          - clib-search.exe
        skip_cleanup: true
        on:
          tags: true
