include $(top_srcdir)/deps/which/which.mk
include $(top_srcdir)/deps/str-flatten/str-flatten.mk
include $(top_srcdir)/deps/clib-package/clib-package.mk
include $(top_srcdir)/deps/mkdirp/mkdirp.mk
include $(top_srcdir)/deps/path-normalize/path-normalize.mk
include $(top_srcdir)/deps/path-join/path-join.mk
include $(top_srcdir)/deps/str-starts-with/str-starts-with.mk
include $(top_srcdir)/deps/str-ends-with/str-ends-with.mk
include $(top_srcdir)/deps/parse-repo/parse-repo.mk
include $(top_srcdir)/deps/debug/debug.mk
include $(top_srcdir)/deps/wildcardcmp/wildcardcmp.mk
include $(top_srcdir)/deps/commander/commander.mk
include $(top_srcdir)/deps/wiki-registry/wiki-registry.mk
include $(top_srcdir)/deps/gumbo-parser/gumbo-parser.mk
include $(top_srcdir)/deps/substr/substr.mk
include $(top_srcdir)/deps/gumbo-text-content/gumbo-text-content.mk
include $(top_srcdir)/deps/gumbo-get-element-by-id/gumbo-get-element-by-id.mk
include $(top_srcdir)/deps/gumbo-get-elements-by-tag-name/gumbo-get-elements-by-tag-name.mk
include $(top_srcdir)/deps/trim/trim.mk
include $(top_srcdir)/deps/list/list.mk
include $(top_srcdir)/deps/case/case.mk
include $(top_srcdir)/deps/fs/fs.mk
include $(top_srcdir)/deps/tempdir/tempdir.mk
include $(top_srcdir)/deps/str-replace/str-replace.mk
include $(top_srcdir)/deps/occurrences/occurrences.mk
include $(top_srcdir)/deps/strdup/strdup.mk
include $(top_srcdir)/deps/str-concat/str-concat.mk
include $(top_srcdir)/deps/asprintf/asprintf.mk
include $(top_srcdir)/deps/logger/logger.mk
include $(top_srcdir)/deps/console-colors/console-colors.mk
include $(top_srcdir)/deps/parson/parson.mk
include $(top_srcdir)/deps/http-get/http-get.mk
